mupq/mupq

- common/sha2.c
- common/sha2.h
I took the `sha2.c` and `sha2.h` from PQClean, because some schemes will need SHA-256 and the incremental API, and added the code for hashing measurements. This should avoid counting parts twice.
> Add SHA-{224,256} and incremental SHA-2 variants

- crypto_sign/stack.c
This reduced the stack measurements by 8 bytes for all schemes.
I cannot really explain this, but it should matter too much.
However, when rebenchmarking this in the future we should be aware of this.
> Update PQClean to update Dilithium, slightly modify stack benchmark

- common/fips202.c
I've noticed that the incremental shake128 didn't produce the same testvectors as the normal shake128. 
This was due to a mistake I made when porting the incremental API in `fips202.c` to pqm4. 
Since the fips202.c is used for both the host and the m4, this was not caught by the testvectors test. 
It might be worth to compare testvector/nistkat hashes to the ones specified in the `META.yml` from PQClean. This would catch such mistakes in the future.
> Fix stupid mistake in our fips202.c

- crypto_kem/test.c
- crypto_sign/test.c
The sk, pk, message, ... buffers aren't necessarily aligned to a machine word, so the canary check shouldn't assume this. On some platforms these checks fail.
> Fix canary checks for platforms which can't do unaligned access

- common/aes.c
Ports https://github.com/PQClean/PQClean/pull/198 to mupq for compatibility. 
We also implement it as an empty function.
> Add relaese function for AES key schedule

- common/sha2.c
I found yet another bug in the incremental sha512. 
See https://github.com/PQClean/PQClean/pull/232
This is now also tested against NIST KATs now in PQClean. 
**Note that one of the schemes in mupq/pqm4 actually used this incremental API. So we don't have to rebenchmark anything**
> Fix incremental sha512

- crypto_kem/stack.c
- crypto_kem/testvectors-host.c
- crypto_sign/stack.c
- crypto_sign/testvectors-host.c
- mupq.py
This fixes #24 and mupq/pqm4#111. It also makes all these different print functions slightly more similar.
> Fix Python 3.6 compatibility and dubious use of printf

- common/sendfn.h
- crypto_kem/hashing.c
- crypto_kem/speed.c
- crypto_kem/stack.c
- crypto_sign/hashing.c
- crypto_sign/speed.c
- crypto_sign/stack.c
The refactoring removes a lot of identical duplicated code.
Avoiding the printf functions reduces code size *considerably*. This is may not
be necessary for platforms with larger flash sizes as in PQM4, however the
printf functions for RISC-V pull in a lot of code. There are the "nano" variants
of the libc, which are small enough. However, these don't support printing long
longs which we need for the cycle counts.
The code for unsigned long long printing uses a division by 10 trick from
hackers delight, since the compiler will otherwise use a generic 64-bit division
code, which is quite a bit larger.
> Refactor number printing functions and avoid Xprintf functions

- crypto_kem/r5n1-1kemcca-0d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5n1-1kemcca-0d/opt/round5_variant_setting.h
- crypto_kem/r5n1-3kemcca-0d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5n1-3kemcca-0d/opt/round5_variant_setting.h
- crypto_kem/r5n1-5kemcca-0d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5n1-5kemcca-0d/opt/round5_variant_setting.h
- crypto_kem/r5nd-1kemcca-0d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5nd-1kemcca-0d/opt/round5_variant_setting.h
- crypto_kem/r5nd-1kemcca-5d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5nd-1kemcca-5d/opt/round5_variant_setting.h
- crypto_kem/r5nd-3kemcca-0d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5nd-3kemcca-0d/opt/round5_variant_setting.h
- crypto_kem/r5nd-3kemcca-5d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5nd-3kemcca-5d/opt/round5_variant_setting.h
- crypto_kem/r5nd-5kemcca-0d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5nd-5kemcca-0d/opt/round5_variant_setting.h
- crypto_kem/r5nd-5kemcca-5d-sneik/opt/round5_variant_setting.h
- crypto_kem/r5nd-5kemcca-5d/opt/round5_variant_setting.h
In #36 it was noted that in our Round5 adaptions, we did not select the correct parameters for the underlying CCA-secure KEMs. This fixes that.
> Fix Round5 CCA KEM

- mupq.py
Since the `size` utility is platform dependent, it should be configurable. I made the ARM variant the default for the moment, so you don't have to patch pqm4.
> Make the size executable configurable

- mupq.py
https://github.com/PQClean/PQClean/pull/253 adds AESNI implementations of SPHINCS+.
https://github.com/PQClean/PQClean/pull/259 adds SSE implementations of McEliece.
Those obviously won't work on mupq targets, so I added those to the current
blacklist. In case more implementation types are added to pqclean in the future
we might want to switch a more clean filtering approach.
> Skip AESNI and SSE implementations 

- common/sha2.c
https://github.com/PQClean/PQClean/commit/a655ec8a9d86eadd0cffe1f3b16f5e6e2ead7b94 added sha2_destory functions to the SPHINCS+ implementations.
As we have a stack-based implementations, these are no-ops.
> Add empty sha2_destroy functions

- mupq.py
There is an unreported bug present where _wait_for_start will read
garbage from the chip *before* the first '=' char is received.
It occurs when the chip is not synced with the benchmarking
script, and is running an implementation without the benchmarking
script listening.  In this case, there is still data in the serial
buffer from a lost (unsynced) benchmark run.
This commit flushes (i.e. erases) the contents of the serial buffer
before trying to sync to the '=' chars coming from the chip.
> python: Flush the serial buf chip sync

- common/crypto_hashblocks_sha512.h
- common/sha2.c
[supercop20200409](https://bench.cr.yp.to/supercop/supercop-20200409.tar.xz) shipped a  fast m4 implementation of `crypto_hashblocks_sha512` which is used by a number of schemes in [pqm4](https://github.com/mupq/pqm4). This PR makes the necessary changes in [mupq](https://github.com/mupq/mupq) to allow the sub-projects to provide their own specialized implementation of `crypto_hashblocks_sha512`.
> outsource crypto_hashblocks_sha512

- crypto_kem/testvectors-host.c
- crypto_kem/testvectors.c
For NTRUPrime, we ran into the problem that the reference implementation samples randomness in rather small 4-byte chunks, while the optimized implementation uses larger chunks. 
The resulting testvectors are exactly the same, but pqm4/mupq still complained because 
`randombytes(x, 1); randombytes(x, 1);` results in printing `AB\nCD\n` while `randombytes(x, 2);` results in printing  `ABCD\n`. 
I removed the `printbytes()` from the `randombytes()` in this PR as I cannot think of any purpose this serves other than debugging. Note that for signatures, we somehow never had a `printbytes()` in there. This difference seems to date back to the very first days of pqm4.
> Remove printbytes from randombytes

- crypto_kem/hashing.c
- crypto_kem/speed.c
- crypto_kem/stack.c
- crypto_sign/hashing.c
- crypto_sign/speed.c
- crypto_sign/stack.c
- mupq.py
When doing the new benchmarks, I sometimes ran into the problem that the
speed benchmarks contained something like
keypair cycles:
6639120105
keypair cycles:
6639120105
sign cycles:
103762136231
verify cycles:
154024957
So for what ever reason, the board was reset after the first key gen was done.
Our parsing script didn't really handle this well as it was based on line
numbers. I made that more robust in this patch.
I also made it a bit more consistent across benchmarks.
> More robust result parsing

- crypto_sign/stack.c
Hi,
This PR aligns the stack measurement program with the speed benchmark to save on memory consumption. This prevents overflows when running schemes with large signature sizes.
Thanks for your consideration.
> Save memory space on stack measurement for signatures

- common/fips202.c
Considering that the loop consumes full blocks, line 50 should just update the state with the remaining bytes.
> Potential fix to the kyber512 issue.

- common/fips202.c
Our current fips202.c implementation is fairly wasteful in terms of stack usage by always allocating an extra 200-byte state.
That is rather stupid. I've refactored it to not use that additional buffer. I do not see any significant impact on the cycle counts by this change.
This wants a bit more testing before it can be merged.
> Optimize stack consumption of fips202.c

- crypto_kem/stack.c
- crypto_sign/stack.c
In some rare cases, the incremental step of the `canary_size` will overflow the `MAX_STACK_SIZE`, even though the scheme still fits. This will do at least one additional run with the absolute maximum stack size.
> Stack size cap

- crypto_kem/hashing.c
- crypto_kem/speed.c
- crypto_kem/stack.c
- crypto_kem/test.c
- crypto_kem/testvectors-host.c
- crypto_kem/testvectors.c
- crypto_sign/hashing.c
- crypto_sign/speed.c
- crypto_sign/stack.c
- crypto_sign/test.c
- crypto_sign/testvectors-host.c
- crypto_sign/testvectors.c
Clang complains about x####y -- it should be x##y. 
The error only occured in `testvectors-host.c`, but I fixed it in all the sources.
> Fix testvectors when cc=clang

- mupq.py
Right now the testvectors script does not work when bin_type is not .bin, e.g.,
it is .hex for the nucleo-l4r5zi. It fails when trying to build the host binary.
The script tries to build
bin-host/scheme_impl_testvectors.hex rather than
bin-host/scheme_impl_testvectors.
This is caused by a replace('.bin', '').
> Fix testvectors when bin_type is not .bin

- genskiplist.py
I used this script to generate the `skiplist.py` files in `pqm{4,3}`. It takes the output files from the `mps2-an386` target, when run via the make script, i.e., compile `pqm{4,3}` with the `mps2-an38{6,5}` plattform and the `run-stack-tests` targets.
```sh
cp -r benchmarks benchmarks.bak # Remember to backup your benchmark folder!
make clean # Because this will delete it
make PLATFORM=mps2-an386 -j4 run-stack-tests # This generates a bunch of frommake files in the benchmarks folder
find benchmarks -name frommake -exec mupq/genskiplist.py {} + > skiplist.py
```
> Add script for generating the skiplists

- common/hal.h
- crypto_kem/stack.c
- crypto_sign/stack.c
Adds an API to spray the stack and check the number of changed bytes. This should return better results than the platform independent approach, and doesn't require the iterative increase of the stack canary. However, the platform HALs have to implement this functionality in assembly.
> New HAL API for stack spraying/checking

- crypto_kem/test.c
- crypto_sign/test.c
- mupq.py
- platforms.py
This revamps the entire logging of `mupq`. Pretty much kicks out all the logging from the console, except errors and test pass/fail messages. This frees up the clutter and makes space for a progress bar. The bar is based on the `tqdm` package, which also has support for time tracking etc.
For even longer tests, I also added progress tracking for the longer running tests. Especially the `test` and `speed` test can be quite long-running due to their many iterations, so the gui comes with stacked progress bars (one for the schemes, one for the iterations).
Since a full log is still useful, the full log is dumped into a `mupq.log` file, which is rotated ten times so you don't immediately loose previous runs.
> Progressbar for the console

- common/crypto_declassify.h
McEliece uses a `crypto_declassify.h` header. It doesn't do anything platform dependent, so I just symlinked it.
> Symlink to missing header used by ClassicMcEliece

- README.md
- common/aes-publicinputs.h
- common/aes.h
- common/compat.h
- common/crypto_hashblocks_sha512.h
- common/fips202.c
- common/fips202.h
- common/hal.h
- common/sendfn.h
- crypto_kem/hashing.c
- crypto_kem/speed.c
- crypto_kem/stack.c
- crypto_kem/test.c
- crypto_kem/testvectors-host.c
- crypto_kem/testvectors.c
- crypto_sign/hashing.c
- crypto_sign/speed.c
- crypto_sign/stack.c
- crypto_sign/test.c
- crypto_sign/testvectors-host.c
- crypto_sign/testvectors.c
- genskiplist.py
- mk/config.mk
- mk/host-crypto.mk
- mk/rules.mk
- mk/schemes.mk
- mupq.py
- platforms.py
To enable re-use in https://github.com/pq-code-package/mlkem-c-embedded. This is applied only to the sources of pqm4 itself that are to a vast degree written by the pqm4 maintainers.
The scheme implementations plus symmetric primitives have other licenses.
> Adds Apache-2.0 license in addition to CC0

- crypto_sign/hashing.c
- crypto_sign/speed.c
- crypto_sign/stack.c
Fixes https://github.com/mupq/mupq/issues/160.
Note that no additional checks are needed in `mupq.py`, since `SpeedBenchmark` and `HashingBenchmark` derive from `StackBenchmark`:
https://github.com/mupq/mupq/blob/21dbaf66627cbb3ac326e4b695a70b13e21d3914/mupq.py#L314
https://github.com/mupq/mupq/blob/21dbaf66627cbb3ac326e4b695a70b13e21d3914/mupq.py#L321
and neither overrides the `run_test` method, which in `StackBenchmark` already checks for errors:
https://github.com/mupq/mupq/blob/21dbaf66627cbb3ac326e4b695a70b13e21d3914/mupq.py#L308
> Check if signatures are accepted in benchmarks
